import { Inter } from "next/font/google";
import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

import GlobalProvider from "@/components/hoc/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                controlHeight: 38,
                controlHeightLG: 44,
                controlHeightSM: 32,
                colorPrimary: "#1890ff",
              },
            }}
          >
            <GlobalProvider>{children}</GlobalProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
